version: '3.3'

services:
  api:
      build: api
      command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
      volumes:
        - ./api:/app
      ports:
        - "8000:8000"

  frontend:
    build: frontend
    command: npm run dev

    volumes:
      - ./api/output_images:/app/public/output_images
      - ./frontend:/app

    ports:
      - "3000:3000"